### ISSUE TITLE
"Invalid Json" error to list the line/section that had the issue 

### ISSUE THREAD

**Issue by vidu333** [saadq/resumake.io#113]
I wanted to reorder some sections and I downloaded and edited the json by hand. I got an "Invalid JSON" error when trying to upload the edited json and resolved the errors by using jsonlint.com.

If possible and if it makes sense to do, could you list the exact json error? I am using Microsoft Edge so if another browser is recommended let me know.

**Comment by saadq** [comment]
Hey @vidu333 thanks for your suggestion.

It is possible, though I don't really see much benefit in adding JSON linting to the app, I think that responsibility should fall on text editor tools or websites like you mentioned.

With that said, there already is a built in way to reorder sections so you shouldn't have to manually edit the JSON for that anyways: https://github.com/saadq/resumake.io/issues/40#issuecomment-362837888
