### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by xinbinhuang** [saadq/resumake.io#119]
Hi Saad,

Thanks for the good work. I really like the project and the way it standardize the resume making. However, I got some dependency issues (i.e. latex) when I tried to spin up a local server with the latest update on `About` section from the master branch. I think it would be nice to dockerize both the client & server to have a better development and deployment experiences. 

Let me know how do you feel about this. I can submit a PR to add Docker if you are down to the idea.

Thanks 
Bin

**Comment by hefedev** [comment]
OP are you woking on this currently ?
@saadq what do you think? do we have the go

**Comment by saadq** [comment]
Sorry guys! Going through cleaning up my GitHub issues and I somehow missed this issue very sadly... but I think Dockerizing Resumake would be awesome! I personally have no experience with Docker so I probably wouldn't be able to even look into it until `v3` has finished, but if either @xinbinhuang or @hefedev are still interested in helping out with this I would really appreciate it!

Again, sorry for not responding on this for so long.

**Comment by 0xAnselm** [comment]
Hi. Are you intersted in a Docker approach for resumake??

**Comment by ducaale** [comment]
We now have shifted LaTeX generation to client-side, removing the need to install LaTeX locally 🎉.
