### ISSUE TITLE
generate resume api 500 error

### ISSUE THREAD

**Issue by rrr523** [saadq/resumake.io#133]
**Describe the bug**
generate resume api 500 error

**To Reproduce**

1. click "make" button , it called 500.

**Expected behavior**

generate resume successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/59029880/82942565-b9583f80-9fca-11ea-97dc-a42e5c5a7ab2.png)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]
 - Version [83]

**Additional context**

I local start Node server, it throw error:

![image](https://user-images.githubusercontent.com/59029880/82942679-ea387480-9fca-11ea-81c7-3cc4cf25006a.png)

**Comment by saadq** [comment]
It's basically as the error states, you are unable to run the `xelatex` command on your machine. Check out the [Requirements section](https://github.com/saadq/resumake.io/blob/master/contributing.md#requirements) in the contributing doc, you will need to have LaTeX installed with the ability to run `pdflatex`, `xelatex`, and `lualatex` from the command line. If any of those commands don't exist, you will need to install them (i.e. search for "install xelatex on mac" on google)
