### ISSUE TITLE
Run from network server instead of localhost

### ISSUE THREAD

**Issue by mcuix** [saadq/resumake.io#134]
I have resumake.io installed on a local raspberry pi server, but am unable to connect to it via http://<ip-address>:3000. Which files do I need to edit to change the localhost to the ip of the local pi.

**Comment by saadq** [comment]
From what I understand, this isn't a question/issue specific to Resumake, so I would recommend maybe asking on StackOverflow to find out how to run a Node server from a network server instead of localhost.
