### ISSUE TITLE
[Question] How to create a new section?

### ISSUE THREAD

**Issue by scheung38** [saadq/resumake.io#135]
For example a Profile section at the beginning of the page?

Also how to drag and drop, or insert within, say the WORK section as currently if adding a new section we need to delete existing subsection?

**Comment by saadq** [comment]
Hi @scheung38, unfortunately both of these are currently features that aren't supported unfortunately. 

Issue for allowing reordering: https://github.com/saadq/resumake.io/issues/40
Issue for allowing custom sections: https://github.com/saadq/resumake.io/issues/97

I am currently developing version 3 of Resumake which will support both of these features. You can track progress for v3 here: https://github.com/saadq/resumake.io/issues/63

Implementation for reordering is basically already done, I am currently working on custom sections.

**Comment by scheung38** [comment]
Is that reordering of contents, say within WORK section? Say I needed to insert a missing work experience? I am not referring to reordering of the sections as that is already working...

**Comment by saadq** [comment]
Yes, I am referring to reordering of subsections, not sections. I have  it working in the new v3 of Resumake:

![reorder](https://user-images.githubusercontent.com/5678694/83957815-a3931780-a81f-11ea-93fb-92041c1a75ed.gif)

but it will be some time before v3 is finished and released.

**Comment by scheung38** [comment]
so users need to wait for your nice work then?

**Comment by saadq** [comment]
Unfortunately yes :/

I'm working on this on my free time during weekends so hoping to make some more progress by the end of this weekend, but I think it will probably be a few more weeks of work.

**Comment by scheung38** [comment]
A publications section would be nice too, but a profile summary I believe would be the most asked...

**Comment by gauravdhiman** [comment]
I think profile summary is something which most of the users would require. It will be good to have an option of custom section that can be placed anywhere. I like the custom section of [www.resume.com](www.resume.com), it's a free rich text section so one can use that for any purpose like summary or publications or interests etc. I am looking forward to v3 as that seems to be very promising. Thanks @scheung38 for putting all your efforts to make such a great and free resume builder.

**Comment by gauravdhiman** [comment]
Is it somehow possible to have a custom section available quickly without much effort ? If you can make custom section work, I think that will address many use-cases.

**Comment by gauravdhiman** [comment]
@saadq is there any update on when the custom section will be available on resumake.io
If you can document the steps for local setup that will be helpful. I would like to try v3 in local and see if I can use the custom section or not.
