### ISSUE TITLE
Can't display anything on either Brave or Chrome

### ISSUE THREAD

**Issue by aleczandah** [saadq/resumake.io#149]
![image](https://user-images.githubusercontent.com/70264361/91288930-43ff3500-e79a-11ea-991e-b4f3654160c7.png)

Just get a blank page whatever I do!

**Comment by bshan7** [comment]
The 'MAKE' button should be clicked inorder to process your information and display it on your desired template. It will not be updated simultaneously as you type in your details.

**Comment by aleczandah** [comment]
I am SUCH an idiot. Thank you!

**Comment by saadq** [comment]
You're not, it could be more intuitive. You're not the first person who had this issue. Hopefully v3 will make it more clear to new users.

Thanks @bshan7 for answering
