### ISSUE TITLE
what font is used in Template1

### ISSUE THREAD

**Issue by powertrio77** [saadq/resumake.io#154]
Can you tell me the main one or two fonts used in Template1 please?
my guesses are Book Antiqua Constantia, Sitka, but it doesn't really look right. 
I'm trying merge 2 PDF files.

1. tried searching other issues, is:issue is:open font
2. tried looking in resumake.io/app/server/src/generator/templates/template1/ 
can you tell me, where could I see this, which file in the code?  thanks.

**Comment by saadq** [comment]
Someone who knows LaTeX more than I may be able to say with more certainty, but looking at [template1](https://github.com/saadq/resumake.io/blob/master/app/server/src/generator/templates/template1/index.js), it doesn't look like any fonts are specified so it would be using the default font for LaTeX. Doing a search for that seems to suggest that the font would be `Computer Modern` / `Latin Modern`.

**Comment by powertrio77** [comment]
thanks

**Comment by saadq** [comment]
closing, feel free to reopen if needed
