### ISSUE TITLE
Consider generating the LaTeX document in the client-side

### ISSUE THREAD

**Issue by ducaale** [saadq/resumake.io#166]
I have recently come across [SwiftLaTeX](https://github.com/SwiftLaTeX/SwiftLaTeX) which is a client-side LaTex editor that takes advantage of WebAssembly for the document generation. I think it would be nice to do the same for resumake.io since it would be more faster and responsive for live previewing.

**Comment by saadq** [comment]
Thanks for sharing this! This is really cool, going to take a look at this soon when i get a chance and see how performance and stuff is

**Comment by saadq** [comment]
note to self: https://github.com/SwiftLaTeX/SwiftLaTeX/blob/master/src/client/swiftlatex/latexEngine.tsx#L122-L167

**Comment by ducaale** [comment]
SwiftLaTeX refactoring work can be followed at https://github.com/ducaale/SwiftLaTeX/tree/comlink
