### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by OthonoCode** [saadq/resumake.io#168]
Hello! The website has been down all day for me today, May 10th. The last I had accessed it was the morning of May 8th. 

My browser throws ERR_CONNECTION_REFUSED and when I try accessing it on cellular LTE network I get HTTP ERROR 408.

Thank you for your work on this excellent project and I hope you are able to restore it soon!

**Comment by DaivikGoel** [comment]
+1 on this issue. Would be a shame if you took the website down, this is one of my favourite resources to refer people too :(

**Comment by saadq** [comment]
Sorry for the downtime! I had it resolved last night, should be all good now.

and lol dw, there are no plans to take the website down anytime in the foreseeable future :). I do hope to try to get better sponsorship for it at some point though as I have been losing money every month to keep the website up.
