### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by Aditya-ds-1806** [saadq/resumake.io#182]
**Describe the bug**
[https://resumake.io/](https://resumake.io/) is down

**To Reproduce**
1. Go to https://downforeveryoneorjustme.com/resumake.io?proto=https
2. Alternatively, just go to https://resumake.io/

**Expected behavior**
Website must be accessible

**Screenshots**
![image](https://user-images.githubusercontent.com/46485997/148197757-fb0de81c-ec20-45fd-881d-d3c974b47867.png)
https://downforeveryoneorjustme.com/resumake.io?proto=https

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 96.0.1054.34

**Comment by realshovanshah** [comment]
Yup, same for me. In a desperate need for this website rn.

**Comment by SoulEater45** [comment]
Same here

**Comment by saadq** [comment]
Very sorry everyone! Been out of country for a couple of weeks so haven't been able to get a chance to fix it til now. Website should be back up now, please feel free to open an issue if you still encounter any problems.
