### ISSUE TITLE
V3 Not working properly

### ISSUE THREAD

**Issue by qfavor** [saadq/resumake.io#210]
Hello,

I'm trying to setup the project on my local machine, and even though the installation goes without any error, the platform looks like this:
<img width="1638" alt="ResumeMake" src="https://github.com/saadq/resumake.io/assets/54986487/534dd6bd-fa6c-4ff6-8271-d789ef4c7fda">

As you can see, the templates do not display correctly, the Make button does not appear, as well as the Next buttons seem to be missing.

Is there something I am not configuring correctly or the functionality is broken because the platform is still a work in progress?
I believe the project is very useful and I really appreciate the functionalities provided, so I'd really love to play around locally with the features.

Thank you!

**Comment by ducaale** [comment]
Hi @qfavor, the backend part is mostly done, but I'm still working on [porting v2 UI + the remaining sections]( https://github.com/saadq/resumake.io/pull/203) (Hopefully, I will get back to it by the end of this month).

If you would like to help with the v3 rewrite, I would encourage you to join the Resumake Discord channel at https://discord.gg/UYygFCF
