### ISSUE TITLE
Deploying V2 in production

### ISSUE THREAD

**Issue by unu-1** [saadq/resumake.io#211]
Hi,

Can someone please share a quick guide on how to deploy V2 to production? 

I've managed to deploy V3, but I find it hard to contribute to the new version and obtain the same functionalities present in V2. That's why I would like to try out V2 on a live website (I'm using an Azure Web App), and play around with it live until I understand how the functionalities work.

Things I've tried unsuccessfully:
- Deploying using nginx;
- Deploying using docker.

I'd appreciate any pointers at this time.

Thank you!

**Comment by ducaale** [comment]
Hi @qfavor, please take a look at the `contributing.md` file in [v2 branch](https://github.com/saadq/resumake.io/tree/v2-(old)), which documents all the steps necessary to get Resumake v2 running locally.
