### ISSUE TITLE
Use Docker to install and run the app

### ISSUE THREAD

**Issue by AndreaPi** [saadq/resumake.io#225]
I see there's a merged PR to run resumake locally using Docker:

https://github.com/saadq/resumake.io/pull/152

However, there's no Dockerfile in the repository. How can I run this using Docker?

**Comment by ducaale** [comment]
Hi @AndreaPi, with #227 we no longer require LaTeX installation for a simpler setup and enhanced privacy. I will close this issue, but please let me know if you still need Docker to run Resumake locally.

**Comment by AndreaPi** [comment]
@ducaale to let you know if I need Docker, first of all I need to know how to install & run resumake now. There's no install guide in the README.md anymore. How do I install this software?

**Comment by ducaale** [comment]
Hey @AndreaPi, the only requirement is to have Node v20 installed locally. After that, you can run `npm i` to install dependencies and `npm run dev` to run the project.

**Comment by AndreaPi** [comment]
Thanks for the answer @ducaale. I don’t want to install `npm` on my system, so yes, I need Docker to run resumake locally. Can you provide a Dockerfile? Thanks in advance
