### ISSUE TITLE
created the resume  it is not uploading when pressing “make”

### ISSUE THREAD

**Issue by julesxo0** [saadq/resumake.io#233]
hi,
i’ve been editing my resume for hours now and once i was finished and ready to “make” it said file not there and giving me and error and it gives me a blank page when refreshing. i restarted my phone and ipad as i used both to check to see if it was just an iphone issue but on both devices it’s doing the same thing. i’m not sure what else to do as i tried using the other file json but that isn’t working either when converting to a pdf. i used this before and had not issue with viewing the pdf file when finishing the resume. please help :(:(:(
![IMG_3168](https://github.com/saadq/resumake.io/assets/167946035/3a914f49-25e9-472c-974f-2eeb26133e23)
![IMG_3169](https://github.com/saadq/resumake.io/assets/167946035/3ba6312d-ee59-4558-8c0a-658e6e9879d7)

**Comment by devdrowsy** [comment]
Can you share the contents of your JSON file?

**Comment by julesxo0** [comment]
> Can you share the contents of your JSON file?

it’s just the text format of my resume in like code form. i’ve never heard of json before i have no idea what it is.. i don’t want the json file at all tbh i just want to download the pdf but it won’t show up:(

**Comment by devdrowsy** [comment]
Can you attach your JSON file in a comment here like this comment has it? We can look into the issue when you've shared the JSON to see what the problem with it is.

[resume.json](https://github.com/saadq/resumake.io/files/15087789/resume.json)

**Comment by devdrowsy** [comment]
You can do so by using this button 
![test](https://github.com/saadq/resumake.io/assets/98285166/b69bdb84-5ac6-47f4-add4-6eed5a7dd18a)

**Comment by julesxo0** [comment]
okay sure here it is. hope you can help!:)


Resume: `<redacted>`

**Comment by devdrowsy** [comment]
hey @julesxo0, can you try this fixed JSON? 

Fixed JSON: REDACTED

There was an issue with a "zero-width" character being present in the file which is what was causing the PDF generation to fail. It's hard to notice something like that unless you have a good text editor that will let you know there is issues like that.

The problem usually happens from copy/pasting text from something like a PDF into the input fields. Sadly there still needs to be an update on our side to have this problem resolved automatically so in the mean time we'll just have to manually fix JSON files that have issues like this. 

Going forward, I would recommend emailing Saad (the creator) about issues like this and he usually responds fast to emails. You can reach out to him at saadquad@gmail.com

Please let me know once you've downloaded the fixed resume and I will remove it from the comment to avoid sharing your personal information with anyone else that comes upon this issue

**Comment by julesxo0** [comment]
thank you for looking into it! sorry but i’m really unaware with the json file thing i only have used pdf and word docs for resume making lol :/ is there any way you’d be able to convert that for me to a pdf as what i was initially trying to do. i’d really appreciate it if you can do that:))

**Comment by julesxo0** [comment]
> hey @julesxo0, can you try this fixed JSON?
> 
> [fixed.json](https://github.com/saadq/resumake.io/files/15088007/fixed.json)
> 
> There was an issue with a "zero-width" character being present in the file which is what was causing the PDF generation to fail. It's hard to notice something like that unless you have a good text editor that will let you know there is issues like that.
> 
> The problem usually happens from copy/pasting text from something like a PDF into the input fields. Sadly there still needs to be an update on our side to have this problem resolved automatically so in the mean time we'll just have to manually fix JSON files that have issues like this.
> 
> Going forward, I would recommend emailing Saad (the creator) about issues like this and he usually responds fast to emails. You can reach out to him at [saadquad@gmail.com](mailto:saadquad@gmail.com)
> 
> Please let me know once you've downloaded the fixed resume and I will remove it from the comment to avoid sharing your personal information with anyone else that comes upon this issue

n

> hey @julesxo0, can you try this fixed JSON?
> 
> [fixed.json](https://github.com/saadq/resumake.io/files/15088007/fixed.json)
> 
> There was an issue with a "zero-width" character being present in the file which is what was causing the PDF generation to fail. It's hard to notice something like that unless you have a good text editor that will let you know there is issues like that.
> 
> The problem usually happens from copy/pasting text from something like a PDF into the input fields. Sadly there still needs to be an update on our side to have this problem resolved automatically so in the mean time we'll just have to manually fix JSON files that have issues like this.
> 
> Going forward, I would recommend emailing Saad (the creator) about issues like this and he usually responds fast to emails. You can reach out to him at [saadquad@gmail.com](mailto:saadquad@gmail.com)
> 
> Please let me know once you've downloaded the fixed resume and I will remove it from the comment to avoid sharing your personal information with anyone else that comes upon this issue

i just tried using a json to pdf converter on different programs and it isn’t showing up:( really not sure what to do

**Comment by julesxo0** [comment]
> hey @julesxo0, can you try this fixed JSON?
> 
> [fixed.json](https://github.com/saadq/resumake.io/files/15088007/fixed.json)
> 
> There was an issue with a "zero-width" character being present in the file which is what was causing the PDF generation to fail. It's hard to notice something like that unless you have a good text editor that will let you know there is issues like that.
> 
> The problem usually happens from copy/pasting text from something like a PDF into the input fields. Sadly there still needs to be an update on our side to have this problem resolved automatically so in the mean time we'll just have to manually fix JSON files that have issues like this.
> 
> Going forward, I would recommend emailing Saad (the creator) about issues like this and he usually responds fast to emails. You can reach out to him at [saadquad@gmail.com](mailto:saadquad@gmail.com)
> 
> Please let me know once you've downloaded the fixed resume and I will remove it from the comment to avoid sharing your personal information with anyone else that comes upon this issue

i just tried converting the fixed json file to a pdf and it isn’t working, nothing is showing up :/ i’ve never done this before so im super lost

**Comment by julesxo0** [comment]
> hey @julesxo0, can you try this fixed JSON?
> 
> Fixed JSON: REDACTED
> 
> There was an issue with a "zero-width" character being present in the file which is what was causing the PDF generation to fail. It's hard to notice something like that unless you have a good text editor that will let you know there is issues like that.
> 
> The problem usually happens from copy/pasting text from something like a PDF into the input fields. Sadly there still needs to be an update on our side to have this problem resolved automatically so in the mean time we'll just have to manually fix JSON files that have issues like this.
> 
> Going forward, I would recommend emailing Saad (the creator) about issues like this and he usually responds fast to emails. You can reach out to him at [saadquad@gmail.com](mailto:saadquad@gmail.com)
> 
> Please let me know once you've downloaded the fixed resume and I will remove it from the comment to avoid sharing your personal information with anyone else that comes upon this issue

thank you for looking into it! sorry but i’m really unaware with the json file thing i only have used pdf and word docs for resume making lol :/ is there any way you’d be able to convert that for me to a pdf as what i was initially trying to do. i’d really appreciate it if you can do that:))

**Comment by julesxo0** [comment]
> hey @julesxo0, can you try this fixed JSON?
> 
> Fixed JSON: REDACTED
> 
> There was an issue with a "zero-width" character being present in the file which is what was causing the PDF generation to fail. It's hard to notice something like that unless you have a good text editor that will let you know there is issues like that.
> 
> The problem usually happens from copy/pasting text from something like a PDF into the input fields. Sadly there still needs to be an update on our side to have this problem resolved automatically so in the mean time we'll just have to manually fix JSON files that have issues like this.
> 
> Going forward, I would recommend emailing Saad (the creator) about issues like this and he usually responds fast to emails. You can reach out to him at [saadquad@gmail.com](mailto:saadquad@gmail.com)
> 
> Please let me know once you've downloaded the fixed resume and I will remove it from the comment to avoid sharing your personal information with anyone else that comes upon this issue

i just did it on the resumake site it worked!! thank you so much for the help :):) 
please delete fixed resume file you commented when you can :) xx

**Comment by devdrowsy** [comment]
Done :)
