### ISSUE TITLE
Make a 404 Page

### ISSUE THREAD

**Issue by saadq** [saadq/resumake.io#49]
As you can see from going over to https://resumake.io/404 the 404 page doesn't really exist right now. If anyone wants to design/make one, that would be greatly appreciated :)

If anyone wants to work on this I can give some tips on what you would need to do :)

**Comment by jlargs64** [comment]
Hey @saadq , I would like to work on this. What should I need to know/tips?

**Comment by saadq** [comment]
Hey @jlargs64 thanks for volunteering to take this up! So currently, the 404 "page" is coming from [`App.js`](https://github.com/saadq/resumake.io/blob/master/app/client/src/app/App.js):

https://github.com/saadq/resumake.io/blob/69cc228ccb39374fd41dbf4190ee64ad358ccb29/app/client/src/app/App.js#L73

Instead of rendering that function, it should instead point to a 404 component like so:

```js
<Route path="*" component={404} />
```

You would want to create a `404.js` file in `client/src/common/components` and then import that in `App.js` for this to work.

As for what you put in `404.js` that is basically up to you. I don't really have a design in mind for how it should look so you can do whatever you want.

I'm not sure how much experience you have with React or `styled-components` (which is what is used for styling), but you can take a look at some of the other components to see how things are done. And let me know if you have any questions on specific things that I can help with :)

**Comment by jlargs64** [comment]
Sorry to respond so late @saadq ! Had no wifi for a few days. Anyway, I have a basic 404 page made in the components directory and I want to test it but can't see the results when I run the whole project. Any recommendations on how to proceed?

**Comment by saadq** [comment]
It's fine, there's no rush :)

Did you make sure to export the 404 page, and then import it in `App.js`? And then change that line I mentioned above?

If so, it may be easier to help figure out why you cant see the page if you push your current stuff to your fork so that I can take a look!

**Comment by JordanTranchina** [comment]
Hey y'all. I'm a UX designer. Would you like me to build a quick 404 page? Can design it for sure and hopefully code it soon after.

**Comment by saadq** [comment]
@JordanTranchina Sounds great! It is totally up to you if you just want to do the design or code it as well, just let me know. And once again, feel free to ask any questions you may have here or in the [Slack channel](https://join.slack.com/t/resumake/shared_invite/enQtNTMyNzA0NjgwNTMxLTA5NWFmZDJjYjlkNzE0OGNiNDlmMGQ4NGU3ODgyZGMzZjI3MDcxNzlkYjhkOWY3NDI1MWZmYjcwZWIyOTRlMzQ).

**Comment by JordanTranchina** [comment]
hey @saadq can you point me in the direction of the folder where I can make a pull request?

**Comment by saadq** [comment]
You can just create a `design` folder inside `app/client` and put any design assets in there.

**Comment by JordanTranchina** [comment]
Complete as a result of pull request #93

**Comment by saadq** [comment]
Actually I'll leave this open until I create the page based on your design

**Comment by saadq** [comment]
Implemented.

Test: https://resumake.io/blah

<img width="914" alt="screen shot 2019-02-22 at 1 08 43 am" src="https://user-images.githubusercontent.com/5678694/53223161-6c0a5700-363e-11e9-90f8-40bcfac75d7c.png">

Closing, but let me know if you have any issues with the implementation and I can reopen.

**Comment by JordanTranchina** [comment]
This looks great! Glad we got to work together on this!
