### ISSUE TITLE
Hyperlinks are no longer clickable in the generated pdf

### ISSUE THREAD

**Issue by harpreetsingh91** [saadq/resumake.io#52]
In the recent version, any hyperlink added inside resume is not clickable. I have generated pdfs using the service in the past and all hyperlinks (personal website, projects links) were clickable.

**Comment by saadq** [comment]
Hmm, I'll have to look into it. If you don't mind, could you create a minimal example and then download the resume as JSON and upload it here?

**Comment by harpreetsingh91** [comment]
{
  "selectedTemplate": 2,
  "headings": {
    "work": "",
    "skills": "",
    "projects": "",
    "awards": ""
  },
  "basics": {
    "name": "John Smith",
    "email": "johnsmith@gmail.com",
    "website": "mykewlportfolio.com"
  },
  "education": [
    {
      "institution": "Stanford",
      "location": "",
      "area": "Computer Science",
      "studyType": "",
      "startDate": "",
      "endDate": "",
      "gpa": ""
    }
  ],
  "work": [
    {
      "company": "",
      "location": "",
      "position": "",
      "website": "",
      "startDate": "",
      "endDate": "",
      "highlights": [
        ""
      ]
    }
  ],
  "skills": [
    {
      "name": "",
      "level": "",
      "keywords": [
        ""
      ]
    }
  ],
  "projects": [
    {
      "name": "ayyy",
      "url": "coolproject.com",
      "keywords": [
        ""
      ]
    }
  ],
  "awards": [
    {
      "title": "",
      "date": "",
      "awarder": "",
      "summary": ""
    }
  ],
  "sections": [
    "templates",
    "profile",
    "education",
    "work",
    "skills",
    "projects",
    "awards"
  ]
}

**Comment by saadq** [comment]
Hey @harpreetsingh91, I think the issue here is that your URLs are missing `http://` or `https://` prefix. Could you verify this by adding the prefix, downloading the PDF, and then trying to click on the links in the PDF?

**Comment by harpreetsingh91** [comment]
It does work with prefixes!

**Comment by srvstvnhl** [comment]
Please add the HyperLink Text format too. "TextLink" this would be very helpful if you do so. or if there is something to handle this please tell.

**Comment by SG7jit** [comment]
I am able to see the hyperlink in the profile section however this isn't the case with the urls provided in the project link. Can we add hyperlink there?

**Comment by ngmgit** [comment]
I had the same issue and if anyone else is interested they can run the v2-old branch with below changes and fix this.

```
--- a/app/server/src/generator/templates/template1/index.js
+++ b/app/server/src/generator/templates/template1/index.js
@@ -20,7 +20,7 @@ const generator: Template1Generator = {
     const address = (location && location.address) || ''
 
     let line1 = name ? `{\\Huge \\scshape {${name}}}` : ''
-    let line2 = [address, email, phone, website]
+    let line2 = [address, email, phone, `\\href{${website}}{${website}}`]
       .filter(Boolean)
       .join(' $\\cdot$ ')
 
@@ -211,7 +211,7 @@ const generator: Template1Generator = {
         }
 
         if (url) {
-          line1 += `\\hfill ${url}`
+          line1 += `\\hfill \\href{${url}}{${url}}`
         }
 
         if (line1) {
@@ -343,6 +343,7 @@ function template1(values: SanitizedValues) {
     \\pagestyle{empty}
     \\raggedright
     \\usepackage[left=0.8in,right=0.8in,bottom=0.8in,top=0.8in]{geometry}
+    \\usepackage[hidelinks]{hyperref}
 
     ${generator.resumeDefinitions()}
     ```
