### ISSUE TITLE
Use Flow exact types as much as possible everywhere

### ISSUE THREAD

**Issue by saadq** [saadq/resumake.io#57]
For reference: https://flow.org/en/docs/types/objects/#toc-exact-object-types

Flow object types aren't strict by default:

```ts
type Person = {
  name: string
}

function printPerson(person: Person) {
  console.log(person)
}

printPerson({ name: 'john' }) // This works
printPerson({ name: 'john', age: 25 }) // This also works
```

Using exact types with the pipes `|` makes them more strict:

```ts
type Person = {|
  name: string
|}

function printPerson(person: Person) {
  console.log(person)
}

printPerson({ name: 'john' }) // This works
printPerson({ name: 'john', age: 25 }) // This will throw a type error
```

It'd be preferable to use this style as much as possible.

**Comment by alokpant** [comment]
@saadq Can I pick this up? I have not worked with Flow before so would be good topic to get into it.

**Comment by saadq** [comment]
Sure, thanks! Let me know if you have any questions :)

**Comment by alokpant** [comment]
@saadq Cool. I will look into it this week. Will ping you if anything comes up.

**Comment by saadq** [comment]
`v3` has switched over to TypeScript, closing this
