### ISSUE TITLE
Upgrade flow and stop using glow

### ISSUE THREAD

**Issue by saadq** [saadq/resumake.io#62]
`glow` was an alternate format for printing Flow errors back when Flow error messages were pretty bad. They have gotten a lot better in recent versions and running `flow` is generally much faster than running `glow`. It would be a good idea to update `flow` to the latest version, remove the `glow` dependency in both the client/server `package.json` files and updating the npm scripts to use `flow` instead of `glow`.

**Comment by alokpant** [comment]
@saadq I can look into this too while looking at: https://github.com/saadq/resumake.io/issues/57 or do you prefer someone else look into it?

**Comment by saadq** [comment]
It's all yours :)

Again, let me know if you have any questions on anything.
