### ISSUE TITLE
BusinessPlan.Rocks

### ISSUE THREAD

**Issue by MatheusRV** [saadq/resumake.io#65]
Hello, today I would like to propose a new approach to this project. I am a LaTeX enthusiast and believe that WYSWYG tools are a good way to work with such a powerful document editing tool.

Why limit only the creation of curricula vitae? A focus on creating business plans would be very interesting and usual, due to the difficulties of maintaining formatting in a giant document (usually more than 50 pages).

For this it would be necessary some modifications in this project as:
SOON

# Data:
### Entrepreneurs' data (table)
- Name
- Address
- City
- State
- Background
- Attributions

### Sectors of activity (section) (checkbox)
- [ ] Agropecuária
- [ ] Trade
- [ ] Industry
- [ ] Services

### Legal form (section) (radio)
- ( ) Individual Businessman
- ( ) Individual Limited Liability Company - EIRELI
- ( ) Microentrepreneur Individual - MEI
- ( ) Limited society
- ( ) Others:

### Share capital (section) (table)
- No.
- Partner
- Value
- Share (%)

### Customer study (section)
- Target audience (customer profile) (text up to 3000 characters)
- Behavior of customers (interests and what leads them to buy) (text up to 3000 characters)
- Area of ​​coverage (where are customers?) (Text up to 3000 characters)

### Study of competitors (section) (table)
- Company
- Quality
- Price
- Payment conditions
- Location
- Attendance

### Study of suppliers (section) (table)
- Description of the items to be acquired (raw materials, supplies, merchandise)
- Provider's name
- Price
- Deadline
- Payment conditions

## Marketing plan (chapter)
Products and services (section) (text up to 3000 characters)
Price (section) (text up to 3000 characters)
Promotional strategies (section) (text up to 3000 characters)
Marketing structure (section) (text up to 3000 characters)
Location & Justification (section)
- Address 1:
- Address 2:
- City:
- State:
- Phone 1:
- Phone 2:
- Considerations about the point (location), which justify your choice:

## Operational plan (chapter)
Layout (section) (image upload and a textarea with 1000 characters)
Capacity installed (section) What is the maximum production capacity (or services) and commercialization? (text up to 3000 characters)
Operational processes (section) (text up to 4000 characters)
Staff need (section) (table)
- No.
- Position / Function
- Qualifications required

### Fixed investment (section) (tables)
(A) Real Estate
- No.
- Description
Qty
- Unitary value
- Total

(B) Machines
- No.
- Description
Qty
- Unitary value
- Total

(C) Equipment
- No.
- Description
Qty
- Unitary value
- Total

(E) Furniture and Utensils
- No.
- Description
Qty
- Unitary value
- Total

(F) Computers
- No.
- Description
Qty
- Unitary value
- Total

TOTAL OF FIXED INVESTMENTS (A + B + C + D + E + F):

### Initial stock (section) (table)
- No.
- Description
- Qty
- Unitary value
- Total

### Minimum carton (section)
Step 1: Accounts receivable - Calculation of the average term of sales (table)
- Average sales time
- (%)
- Number of days
- Weighted average in days

Step 2: Suppliers - Calculation of the average purchase period (table)
- Average purchase time
- (%)
- Number of days
- Weighted average in days

Step 3: Inventory - Calculation of average inventory requirement (table)
- Average stock requirement
- Number of days

## Strategic evaluation (chapter)

I'll edit as I can think of more ..

**Comment by saadq** [comment]
Hey @MatheusRV, thanks very much for the effort in putting this issue together. While I think this is a cool idea, it is most likely not one I am going to pursue. I have pretty limited time to work on FOSS like Resumake nowadays, and sadly I don't think I would be motivated enough to work on something I wouldn't really use personally. I definitely think the idea itself has good value and should probably be done by someone, but it most likely won't be me. Hope you can understand.
