### ISSUE TITLE
Research.expert

### ISSUE THREAD

**Issue by MatheusRV** [saadq/resumake.io#67]
Many researchers and academics around the world do not know how to use LaTeX for their research. Adopting a WYSWYG can facilitate the massive adoption of the scientific milieu to LaTeX technology.

A survey will almost always consist of some

1. Cover
2. Pre-textual
2.1. Cover sheet
2.2. Summary
2.3. Theme
2.4. List of Illustrations
2.5. List of tables
2.6. List of Abbreviations
2.7. Search problem
2.8. Formulation of hypotheses or research questions
2.9. Justification
3. Textuals
3.1 Introduction
3.2 Review of literature or theoretical framework
3.3 Methodology
3.4 Goals
3.4.1 General objective
3.4.2 Specific objective
3.5 Schedule
3.6 Resources
3.7 References
4. Post-textual
4.1.  Appendix - Optional
4.2. Annex - Optional

**Comment by saadq** [comment]
Closing for the same reason as #65.
