### ISSUE TITLE
Set font size

### ISSUE THREAD

**Issue by nhend** [saadq/resumake.io#69]
Allow the user to scale total font size with a slider/text box

**Comment by nhend** [comment]
How would you do this in LaTeX? I can't get \documentclass to do anything to my Resumake docs

**Comment by saadq** [comment]
So little known fact about me... the reason I made this site was because I sucked at `LaTeX` and didn't want to have to use it. 

With that said, I think the issue might be this: https://tex.stackexchange.com/a/70384/78659

TLDR: 

Instead of something like this:

```latex
\documentclass[16pt, a4paper]{article}
```

you would need to do this:

```latex
\documentclass[16pt, a4paper]{extarticle}
```

**Comment by nhend** [comment]
Well thanks for saving the rest of us. Although the more I use Resumake the more I'm tempted to improve my `LaTeX` and contribute here

**Comment by saadq** [comment]
Going to close this out, feel free to reopen if you still have a concern regarding this.
