### ISSUE TITLE
Remove buttons should be `disabled` when there is nothing left to remove

### ISSUE THREAD

**Issue by saadq** [saadq/resumake.io#77]
For example in the **Education** section, if there is only one school left, the <kbd>Remove School</kbd> button should be disabled because there it only removes if there is more than one school left. 

However, currently it looks like you can click it.

**Current look**:

<img width="705" alt="screen shot 2018-10-08 at 4 34 50 am" src="https://user-images.githubusercontent.com/5678694/46598985-fdc06000-cab3-11e8-82fb-988cf88d52b6.png">

**Desired look**:

It should be `disabled` which won't allow clicks and will make it look dull/greyed out. The remove mini buttons should be updated as well (for example, the button for removing job responsibilities from a job in the **Experience** section).

Feel free to change the styles for the disabled button styles as well!

The styles for it live here:

https://github.com/saadq/resumake.io/blob/c224841c3499789a6a413452cee7b2230ecc228f/app/client/src/common/components/Button.js#L44-L61

**Comment by nirmalks** [comment]
I would like to work on this

**Comment by saadq** [comment]
Awesome! It's all yours @nirmalks. Check out the [contributing.md](https://github.com/saadq/resumake.io/blob/master/contributing.md) if you haven't already, and feel free to ask any questions here if you have any trouble setting up or getting the app running.

**Comment by saadq** [comment]
Fixed by #82.
