### ISSUE TITLE
Specify version requirements in contributing.md

### ISSUE THREAD

**Issue by saadq** [saadq/resumake.io#78]
Because there's a fair amount of new contributors, and I've had some users in the past, there should probably be a notice in the [contributing.md](https://github.com/saadq/resumake.io/blob/master/contributing.md) which mentions that Node v7.6+ is required and npm v5+ is required.

**Comment by Esslamb** [comment]
I can look into this :)

**Comment by alexluong** [comment]
Sorry if this is not the right place to talk about it, but is there any good issue you may need help with, @saadq? I'm comfortable with React and Node, so I should be able to tackle or inspect anything.

**Comment by saadq** [comment]
@alexluong I can definitely use help from someone who has React/Node experience! There are some things that probably aren't listed in the issues so I'll ping you once I have those issues created and you can let me know if any of them interest you.

**Comment by alexluong** [comment]
@saadq Sounds great. Just let me know in the issues when you create them and I'll take a look!

**Comment by saadq** [comment]
Fixed by #79
