### ISSUE TITLE
Can not get client/server launched...

### ISSUE THREAD

**Issue by vfulco** [saadq/resumake.io#92]
A bit of a noob with node.js.  I git cloned, installed globally (including blyss and snappy) and ran tests.

The error message surfaces...

ERR! resumake-client@0.1.0 lint: `blyss | snazzy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the resumake-client@0.1.0 lint script 'blyss | snazzy'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

node.js version is 8.10.0
npm version is 3.5.2
ubuntu 18.04

Ultimately I would like to try this as a serverless app.  Any assistance would be appreciated.  TIA.

**Comment by vfulco** [comment]
Went into both client  and server folders, doing npm install in each.  Site tries to render and fails with new errors.  Back when I know more.

**Comment by saadq** [comment]
Would definitely not recommend installing anything globally. The only other potential issue I see from the details you provided are that you are on a pretty old version of npm. I would recommend upgrading to v5.0.0+ if you can. You can update `npm` just by running `npm install -g npm` 

After getting on a new `npm` version, here are the steps you should need to do:

1. Clone or download the project.
2. Go into the project folder in your terminal, and run `npm run build`. This will basically run `npm install` for both client and server for you.
3. Run `npm start`. This basically runs `npm start` for both client/server. Client will be running on `localhost:3000` and the server will be running on `localhost:3001`.

Let me know if you still have issues after that.

**Comment by vfulco** [comment]
Thanks very much for the quick response.  If anyone else is attempting the above, Ubuntu 18.04 installs a higher level of npm (6.7.0) but then symlinks hide it (maintaining 3.5.2 as the current version).

The way to fix is "hash -d npm" found in this Q&A.

 https://askubuntu.com/questions/1036278/npm-is-incorrect-version-on-latest-ubuntu-18-04-installation.

Trying everything again.
